services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    # ===== SQL SERVER CONFIGURATION =====
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQL_SA_PASSWORD}"
