services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    # ===== SQL SERVER CONFIGURATION =====
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQL_SA_PASSWORD}"

    # ===== PORT SQL Hostport:Containerport =====
    ports:
      - "1433:1433"

    # ===== PERSISTENT STORAGE =====
    volumes:
      - sqlserver-data:/var/opt/mssql
    # ===== HEALTH CHECK =====
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q \"SELECT 1\" > /dev/null || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  rabbitmq:
    image: rabbitmq:4-management

    # ===== PORTS Hostport:Containerport =====
    ports:
      - "5672:5672"
      - "15672:15672"

    # ===== PERSISTENT STORAGE =====
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    
    # ===== HEALTH CHECK =====
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
   
  orderservice:
    # ===== BUILD OUR OWN IMAGE =====
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    # ===== PORT Hostport:Containerport =====
    ports:
      - "8080:8080"    
    # ===== ORDER SERVICE CONFIGURATION =====
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__OrderDbConStr: "Server=sqlserver,1433;Database=MicroserviceLearning_OrderDb;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=True;"
      RabbitMQ__HostName: "rabbitmq"    
    # ===== SERVICE DEPENDENCIES, depends_on: means start them first. if you run order service, docker compose Starts SQL Server and rabbitMQ if they arn't running. 
    # Condition means: SQL Server → wait until container is healthy,  RabbitMQ   → wait until RabbitMQ is healthy  =====
    depends_on:
      sqlserver:
       condition: service_healthy
      rabbitmq:
       condition: service_healthy
  
  inventoryservice:
    restart: unless-stopped
    # ===== BUILD OUR OWN IMAGE =====
    build:
      context: ./InventoryService
      dockerfile: Dockerfile
    # ===== PORT Hostport:Containerport =====
    ports:
      - "8081:8080"
    # ===== INVENTORY SERVICE CONFIGURATION =====
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__InventoryDbConStr: "Server=sqlserver,1433;Database=MicroserviceLearning_InventoryDb;User Id=sa;Password=${SQL_SA_PASSWORD};TrustServerCertificate=True;"
      RabbitMQ__HostName: "rabbitmq"
    # ===== SERVICE DEPENDENCIES, depends_on: means start them first. if you run inventory service, docker compose Starts SQL Server and rabbitMQ if they arn't running. 
    # Condition means: SQL Server → wait until container is healthy,  RabbitMQ   → wait until RabbitMQ is healthy  =====
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  sqlserver-data:
    external: true
    name: sqlserver-learning-data

  rabbitmq-data:
    

  